version: '2'

services:

  web:
    restart: always
    build: .
    command: bash -c "python3 manage.py migrate; python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    links:
      - celery
    depends_on:
      - celery

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.11
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5673:5672"

  celery:
    image: celery
    restart: always
    build: .
    volumes:
      - .:/project
    command: bash -c "celery worker -A ytconverter --loglevel=debug --concurrency=4"
    links:
      - rabbit
    depends_on:
      - rabbit



